In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import sklearn
import sys
import os
import time
import tensorflow as tf
from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for model in mpl, np, pd, sklearn, tf, keras:
    print(model.__name__,model.__version__)
    
    

2.0.0
sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
matplotlib 3.2.2
numpy 1.19.0
pandas 1.0.5
sklearn 0.23.1
tensorflow 2.0.0
tensorflow_core.keras 2.2.4-tf


In [2]:
# index
t = tf.constant([[1,2,3],[4,5,6]]) # 2*3矩阵
print(t)
print(t[:,1:])
print(t[:,1])
b = tf.constant([1,2,3,4,5,6,7]) # 一维向量 7个值
print(b)
c = tf.constant(-1.0,shape=[2,3]) # 2*3
print(c)
print(tf.constant([1,2,3,4,5,6],shape=[2,3])) #指定shape

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor(
[[-1. -1. -1.]
 [-1. -1. -1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [3]:
# opt
print(t+10)
print(tf.square(t))
print(t)
print(tf.transpose(t)) #转置 3*2矩阵
print(t @ tf.transpose(t)) # 2*3 @ 3*2 -->2*2 矩阵相乘

tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


In [4]:
# numpy conversion
print(t.numpy())
print(np.square(t))
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(tf.constant(a))

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [9]:
# Scalars
s = tf.constant(2020)
print(s)
print(s.numpy())
print(s.shape)
s2 = tf.constant(10,shape=[])
print(s2)
print(s2.numpy())

tf.Tensor(2020, shape=(), dtype=int32)
2020
()
tf.Tensor(10, shape=(), dtype=int32)
10


In [10]:
# strings
t = tf.constant("cafe")
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t,unit='UTF8_CHAR')) # scalar标量
print(tf.strings.unicode_decode(t,'UTF-8')) #每个字母进行转换 tensor向量

tf.Tensor(b'cafe', shape=(), dtype=string)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [11]:
# string array
t = tf.constant(['cafe','coffee','咖啡'])
print(t)
print(tf.strings.length(t,unit='UTF8_CHAR'))
print(tf.strings.unicode_decode(t,'UTF-8'))

tf.Tensor([b'cafe' b'coffee' b'\xe5\x92\x96\xe5\x95\xa1'], shape=(3,), dtype=string)
tf.Tensor([4 6 2], shape=(3,), dtype=int32)
<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>


In [12]:
# ragged tensor
# index
r = tf.ragged.constant([[11,12],[21,22,23],[],[41]])
print(r)
print(r[1])
print(r[1:])
print(r[1:3])

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>
tf.Tensor([21 22 23], shape=(3,), dtype=int32)
<tf.RaggedTensor [[21, 22, 23], [], [41]]>
<tf.RaggedTensor [[21, 22, 23], []]>


In [13]:
# ragged tensor ops
r2 = tf.ragged.constant([[51,52],[],[71]])
print(tf.concat([r,r2],axis =0))

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41], [51, 52], [], [71]]>


In [23]:
try:
    # print(tf.concat([r,r2],axis = 1))# 行数不同 报错
    pass
except TypeError as ex:
    print(ex)
    
r3 = tf.ragged.constant([[61,62],[72,73],[],[91,92,93]])
print(tf.concat([r,r3],axis = 1)) #concat当 axis=1  请注意 行数相同  4行

<tf.RaggedTensor [[11, 12, 61, 62], [21, 22, 23, 72, 73], [], [41, 91, 92, 93]]>


In [16]:
# ragged tensor to tensor
print(r3.to_tensor()) # 0全部后补

tf.Tensor(
[[61 62  0]
 [72 73  0]
 [ 0  0  0]
 [91 92 93]], shape=(4, 3), dtype=int32)


In [17]:
# sparse tensor
s = tf.SparseTensor(indices =[[0,0],[1,2]], values=[1,2], dense_shape=[3,4])
print(s)
print(tf.sparse.to_dense(s)) #to_dense 转成密集矩阵

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [18]:
# sparse tensor ops
s2 =  s * 2
print(s2)
print(tf.sparse.to_dense(s2))

try:
    s2 + 1 #无此操作
except TypeError as ex:
    print(ex)

# 矩阵相乘
s3 = tf.constant([[2,4],[1,3],[5,6],[7,8]])
print(tf.sparse.sparse_dense_matmul(s,s3)) # 3x4 * 4x2 --> 3*2 

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([2 4], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[2 0 0 0]
 [0 0 4 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
unsupported operand type(s) for +: 'SparseTensor' and 'int'
tf.Tensor(
[[ 2  4]
 [10 12]
 [ 0  0]], shape=(3, 2), dtype=int32)


In [21]:
# sparse tensor  indices顺序排序否则 to_dense有异常
s = tf.SparseTensor(indices =[[0,2],[0,1]], values=[1,2], dense_shape=[3,4])
print(s)
try:
    #print(tf.sparse.to_dense(s))
    pass
except TypeError as ex:
    print(ex)

s_order = tf.sparse.reorder(s)
print(tf.sparse.to_dense(s_order))

SparseTensor(indices=tf.Tensor(
[[0 2]
 [0 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0 2 1 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [22]:
# variable
v = tf.Variable([[1,2,3],[4,5,6]])
print(v)
print(v.value())
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
[[1 2 3]
 [4 5 6]]


In [25]:
# variable ops
v_assign = v.assign(2* v) #2x3
print(v_assign)
v_add = v_assign.assign_add([[1,1,1],[1,1,1]])
print(v_add)
print(v_add[1].assign([3,3,3]))
print(v_add[0,1].assign(2))


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 6,  4, 14],
       [ 6,  6,  6]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 7,  5, 15],
       [ 7,  7,  7]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 7,  5, 15],
       [ 3,  3,  3]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 7,  2, 15],
       [ 3,  3,  3]])>


In [26]:
# not = 赋值
try:
    v[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment
