In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import os
import sys
import time
import sklearn
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for model in mpl, np, pd, sklearn, keras:
    print(model.__name__, model.__version__)

2.0.0
sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
matplotlib 3.2.2
numpy 1.19.0
pandas 1.0.5
sklearn 0.23.1
tensorflow_core.keras 2.2.4-tf


In [2]:
layer2 = keras.layers.Dense(300)
layer1 = keras.layers.Dense(100,input_shape=[None,5])
layer1(tf.zeros([10, 5]))
#layer1.variables #变量
# y = w * x + b 
#layer1.trainable_variables #可训练变量
#help(layer1) # 查看方法

<tf.Tensor: id=29, shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 

In [3]:
# 回归问题
# 加利福利亚
from sklearn.datasets import fetch_california_housing
#加载数据
housing = fetch_california_housing()
print(housing.DESCR)
print(housing.data.shape)
print(housing.target.shape)


.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block
        - HouseAge      median house age in block
        - AveRooms      average number of rooms
        - AveBedrms     average number of bedrooms
        - Population    block population
        - AveOccup      average house occupancy
        - Latitude      house block latitude
        - Longitude     house block longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
http://lib.stat.cmu.edu/datasets/

The target variable is the median house value for California districts.

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bur

In [4]:
import pprint
#展示数据 查看规律
pprint.pprint(housing.data[0:5])
pprint.pprint(housing.target[0:5])

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])
array([4.526, 3.585, 3.521, 3.413, 3.422])


In [5]:
from sklearn.model_selection import train_test_split

#数据切割 训练集 验证集 测试
x_train_all, x_test, y_train_all, y_test = train_test_split(housing.data, housing.target, random_state=7, test_size=0.25)
x_train, x_valid, y_train, y_valid = train_test_split(x_train_all, y_train_all, random_state=11)

print(x_train.shape, y_train.shape)
print(x_valid.shape, y_valid.shape)
print(x_test.shape, y_test.shape)

(11610, 8) (11610,)
(3870, 8) (3870,)
(5160, 8) (5160,)


In [6]:
from sklearn.preprocessing import StandardScaler

#数据归一化
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_valid_scaled = scaler.transform(x_valid)
x_test_scaled =  scaler.transform(x_test)

In [8]:
# metric
metric = keras.metrics.MeanSquaredError() # mse 均方差
print(metric([5.0],[2.0])) # (5-2)^2 = 9
print(metric([0.0],[1.0])) # (0-1)^2 = 1  -->5  metric累加
metric.reset_states()
print(metric([0.0],[1.0])) # (0-1)^2 = 1


tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
# 手动求导，训练模型

In [10]:
# 1. batch 遍历训练集 metric
#    1.1 自动求导
# 2. epoch结束 验证集 metric
epochs = 100
batch_size = 32
steps_per_epoch = len(x_train_scaled) // batch_size
optimizer = keras.optimizers.SGD()
metric = keras.metrics.MeanSquaredError()

def random_batch(x, y, batch_size =32):
    idx = np.random.randint(0, len(x), size = batch_size)
    return x[idx],y[idx]

model = keras.models.Sequential([
    keras.layers.Dense(30, activation='relu',input_shape=x_train.shape[1:]),
    keras.layers.Dense(1)
])

for epoch in range(epochs):
    metric.reset_states()
    for step in range(steps_per_epoch):
        x_batch,y_batch = random_batch(x_train_scaled,y_train,batch_size)
        with tf.GradientTape() as tape:
            y_pred = model(x_batch)
            loss = tf.reduce_mean(keras.losses.mean_squared_error(y_batch,y_pred))
            metric(y_batch,y_pred)
        grads = tape.gradient(loss,model.variables)
        grads_and_vars = zip(grads,model.variables)
        optimizer.apply_gradients(grads_and_vars) # apply_gradients
        print("\rEpoch", epoch, " train mse:",metric.result().numpy(), end="")
    y_valid_pred = model(x_valid_scaled)
    valid_loss = tf.reduce_mean(keras.losses.mean_squared_error(y_valid_pred, y_valid))
    print("\t", "valid mse: ", valid_loss.numpy())




If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Epoch 0  train mse: 4.3518745 0  train mse: 3.057971 0  train mse: 2.929299 0  train mse: 2.3832974 0  train mse: 2.2926095 0  train mse: 1.9705106 0  train mse: 1.8750824 0  train mse: 1.8538383 0  train mse: 1.8020703 0  train mse: 1.7865103 0  train mse: 1.7473433 0  train mse: 1.7439405  train mse: 1.707716 0  train mse: 1.6948098 0  train mse: 1.6520303 0  train mse: 1.9621495 0  train mse: 1.9554669 0  train mse: 1.9475605 0  train mse: 1.895981  train mse: 1.891682 0  train mse: 3.0101323 0  trai

Epoch 22  train mse: 1.2806416	 valid mse:  1.3865104714274241ain mse: 1.234671 22  train mse: 1.2653755 22  train mse: 1.2620964 22  train mse: 1.2625827 22  train mse: 1.26067141.2702905 22  train mse: 1.2764114 22  train mse: 1.2830596 22  train mse: 1.2814624
Epoch 23  train mse: 1.2814798	 valid mse:  1.388579764717286rain mse: 1.258870623  train mse: 1.2489007 23  train mse: 1.2705833 23  train mse: 1.2661839 23  train mse: 1.2566411  train mse: 1.2533942 23  train mse: 1.2632129 23  train mse: 1.2635767 23  train mse: 1.2705275 23  train mse: 1.2806835  train mse: 1.2808486 23  train mse: 1.284785
Epoch 24  train mse: 1.2779741 24  train mse: 1.2443523 24  train mse: 1.2517081 24  train mse: 1.233981 24  train mse: 1.2901995 24  train mse: 1.298170124  train mse: 1.2933277 24  train mse: 1.2915903 24  train mse: 1.286803 24  train mse: 1.28175 24  train mse: 1.2809379	 valid mse:  1.393048457165204
Epoch 25  train mse: 1.2585578 25  train mse: 1.1904514 25  train mse: 1.2539083 

Epoch 46  train mse: 1.26633	 valid mse:  1.3912623696032638 train mse: 1.2768569 46  train mse: 1.2735518  train mse: 1.2662606 46  train mse: 1.2743638 46  train mse: 1.2811111 46  train mse: 1.2748806 46  train mse: 1.2694597 46  train mse: 1.2797897 46  train mse: 1.2844427 46  train mse: 1.2796092 46  train mse: 1.2789818
Epoch 47  train mse: 1.2620338	 valid mse:  1.3838329686076327921 47  train mse: 1.2509809 47  train mse: 1.2391349 47  train mse: 1.226333 47  train mse: 1.2406689 47  train mse: 1.2251259 47  train mse: 1.231163 47  train mse: 1.236189 train mse: 1.2529346 47  train mse: 1.2583644 47  train mse: 1.2603532
Epoch 48  train mse: 1.2463421	 48  train mse: 1.2679604 48  train mse: 1.2991143 48  train mse: 1.285708748  train mse: 1.2606721 48  train mse: 1.2479789 48  train mse: 1.2481421 48  train mse: 1.2430577 48  train mse: 1.2504032 48  train mse: 1.247921 48  train mse: 1.2452836 valid mse:  1.3870904456764321
Epoch 49  train mse: 1.243665	 valid mse:  1.386521

Epoch 71  train mse: 1.2813854	 valid mse:  1.38375667950105ain mse: 1.3099415 1.293999271  train mse: 1.2901461 71  train mse: 1.2865598 71  train mse: 1.2817086 71  train mse: 1.2740401 71  train mse: 1.2766379 71  train mse: 1.2777604  train mse: 1.2805115
Epoch 72  train mse: 1.2258749 72  train mse: 1.2411147 72  train mse: 1.262975 72  train mse: 1.2388326 72  train mse: 1.2468107 72  train mse: 1.2613264 72  train mse: 1.2568198 72  train mse: 1.2430546 72  train mse: 1.2364492 train mse: 1.2317692 72  train mse: 1.2288182	 valid mse:  1.3868295113932385
Epoch 73  train mse: 1.2650487	 valid mse:  1.3880886483745947ain mse: 1.2456412 73  train mse: 1.2245443 73  train mse: 1.2808233 73  train mse: 1.2994142 73  train mse: 1.27532 train mse: 1.2744524 73  train mse: 1.2788923 73  train mse: 1.2742771 73  train mse: 1.2746347 73  train mse: 1.2679032 73  train mse: 1.270397 73  train mse: 1.2641463
Epoch 74  train mse: 1.2662122 1.28267 74  train mse: 1.287411 74  train mse: 1.300

Epoch 96  train mse: 1.2705266 96  train mse: 1.2762046 96  train mse: 1.2419419 96  train mse: 1.2575446 96  train mse: 1.2352809 96  train mse: 1.2516092 96  train mse: 1.249722696  train mse: 1.2384487 96  train mse: 1.2494309 96  train mse: 1.2523571 96  train mse: 1.2580422	 valid mse:  1.3839705323502736
Epoch 97  train mse: 1.2436273	 valid mse:  1.3883244027909934874 97  train mse: 1.2582383 97  train mse: 1.2605215 97  train mse: 1.2598627 97  train mse: 1.258358 97  train mse: 1.2447475 97  train mse: 1.2437235 97  train mse: 1.246406 97  train mse: 1.2557706
Epoch 98  train mse: 1.2519162	 valid mse:  1.3855057462848186ain mse: 1.26686741.29046121.2517986 98  train mse: 1.2612975 98  train mse: 1.2631447 98  train mse: 1.2612033 98  train mse: 1.2550496 98  train mse: 1.2609777 98  train mse: 1.2649916 98  train mse: 1.2580581 98  train mse: 1.2554877
Epoch 99  train mse: 1.2715746	 valid mse:  1.385293436338815 mse: 1.3102059 99  train mse: 1.3154787 99  train mse: 1.300945